// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api"
	mock "github.com/stretchr/testify/mock"
)

// WarnUpd is an autogenerated mock type for the WarnUpd type
type WarnUpd struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *WarnUpd) Execute(_a0 string, _a1 tgbotapi.Update) {
	_m.Called(_a0, _a1)
}
